# Generated by Django 4.2.1 on 2023-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('Category_Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
