# Generated by Django 4.2.1 on 2023-05-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Product_Price', models.IntegerField(blank=True, null=True)),
                ('Product_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='Product Image')),
            ],
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='Category_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Category Image'),
        ),
    ]
