# Generated by Django 4.2.1 on 2023-05-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='Mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
