# Generated by Django 4.2.1 on 2023-05-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userdb_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='Name',
            new_name='Username',
        ),
    ]
