# Generated by Django 4.2.1 on 2023-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_remove_userdb_email_remove_userdb_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='Email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='Mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
