# Generated by Django 4.2.1 on 2023-05-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_userdb_email_userdb_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='Mobile',
        ),
    ]
