# Generated by Django 4.2.1 on 2023-06-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_cartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Image',
            new_name='Cart_Image',
        ),
    ]
