# Generated by Django 4.2.1 on 2023-06-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_rename_image_cartdb_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Cart_Image',
        ),
    ]
