# Generated by Django 4.2.1 on 2023-06-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_checkoutdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutdb',
            old_name='Mobile',
            new_name='Contact',
        ),
    ]
